version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:xe
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - oracle-db

  oracle-db:
    image: oracle/database:18.4.0-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: 
